import Header from '@/components/Header'
import './globals.css'
import { ReactQueryProvider } from './react-query-provider'

export const metadata = {
  title: 'fundus',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <Header />
          <main className='min-h-screen bg-white'>
            <div className=' h-24'/>
            {children}
            <div className=' h-24'/>
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
